CREATE TABLE [dbo].[T_MokuhyoTasseiHyoka] (
    [ShainCd]            CHAR (4)        NOT NULL,
    [HyokaNendo]         CHAR (4)        NOT NULL,
    [HyokaGroupCd]       CHAR (3)        NOT NULL,
    [Mokuhyo1SbtCd]      CHAR (3)        NULL,
    [Mokuhyo1Naiyo]      NVARCHAR (50)   NULL,
    [Mokuhyo2SbtCd]      CHAR (3)        NULL,
    [Mokuhyo2Naiyo]      NVARCHAR (50)   NULL,
    [Mokuhyo3SbtCd]      CHAR (3)        NULL,
    [Mokuhyo3Naiyo]      NVARCHAR (50)   NULL,
    [Mokuhyo4SbtCd]      CHAR (3)        NULL,
    [Mokuhyo4Naiyo]      NVARCHAR (50)   NULL,
    [Mokuhyo5SbtCd]      CHAR (3)        NULL,
    [Mokuhyo5Naiyo]      NVARCHAR (50)   NULL,
    [FurikaeriKeizoku]   NVARCHAR (400)  NULL,
    [FurikaeriMondaiten] NVARCHAR (400)  NULL,
    [FurikaeriTry]       NVARCHAR (400)  NULL,
    [SoHyo]              NVARCHAR (1000) NULL,
    [DisplayOrder]       CHAR (4)        NULL,
    [Hyokasha1Cd]        CHAR (4)        NULL,
    [Hyokasha1Comment]   NVARCHAR (1000) NULL,
    [Hyokasha2Cd]        CHAR (4)        NULL,
    [Hyokasha2Comment]   NVARCHAR (1000) NULL,
    [DelFlg]             CHAR (1)        NOT NULL DEFAULT 0,
    [CrtKojinCd]         CHAR (4)        NOT NULL,
    [CrtDt]              DATETIME2 (7)   NOT NULL,
    [CrtPlgId]           VARCHAR (10)    NOT NULL,
    [LastUpdKojinCd]     CHAR (4)        NOT NULL,
    [LastUpdKojinDt]     DATETIME2 (7)   NOT NULL,
    [LastUpdPlgId]       VARCHAR (10)    NOT NULL,
    [RowVersion]         ROWVERSION      NOT NULL,
    CONSTRAINT [PK_T_MokuhyoTasseiHyoka] PRIMARY KEY CLUSTERED ([ShainCd] ASC, [HyokaNendo] ASC),
    CONSTRAINT [FK_T_MokuhyoTasseiHyoka_M_Shain_1] FOREIGN KEY ([ShainCd]) REFERENCES [dbo].[M_Shain] ([ShainCd]),
    CONSTRAINT [FK_MokuhyoTasseiHyoka_M_HyokaGroup_2] FOREIGN KEY ([HyokaNendo], [HyokaGroupCd]) REFERENCES [dbo].[M_HyokaGroup] ([HyokaNendo], [HyokaGroupCd]),
    CONSTRAINT [FK_MokuhyoTasseiHyoka_M_MokuhyoSbt_3] FOREIGN KEY ([Mokuhyo1SbtCd]) REFERENCES [dbo].[M_MokuhyoSbt] ([MokuhyoSbtCd]),
    CONSTRAINT [FK_MokuhyoTasseiHyoka_M_MokuhyoSbt_4] FOREIGN KEY ([Mokuhyo2SbtCd]) REFERENCES [dbo].[M_MokuhyoSbt] ([MokuhyoSbtCd]),
    CONSTRAINT [FK_MokuhyoTasseiHyoka_M_MokuhyoSbt_5] FOREIGN KEY ([Mokuhyo3SbtCd]) REFERENCES [dbo].[M_MokuhyoSbt] ([MokuhyoSbtCd]),
    CONSTRAINT [FK_MokuhyoTasseiHyoka_M_MokuhyoSbt_6] FOREIGN KEY ([Mokuhyo4SbtCd]) REFERENCES [dbo].[M_MokuhyoSbt] ([MokuhyoSbtCd]),
    CONSTRAINT [FK_MokuhyoTasseiHyoka_M_MokuhyoSbt_7] FOREIGN KEY ([Mokuhyo5SbtCd]) REFERENCES [dbo].[M_MokuhyoSbt] ([MokuhyoSbtCd]),
    CONSTRAINT [FK_T_MokuhyoTasseiHyoka_M_Shain_8] FOREIGN KEY ([Hyokasha2Cd]) REFERENCES [dbo].[M_Shain] ([ShainCd]),
    CONSTRAINT [FK_T_MokuhyoTasseiHyoka_M_Shain_9] FOREIGN KEY ([Hyokasha2Cd]) REFERENCES [dbo].[M_Shain] ([ShainCd])
);
